### ISSUE TITLE
Dashboard incompatible with OpenTelemetry.Instrumentation.Runtime - expects .NET 9 built-in metric names instead of process.runtime.dotnet.* names

### ISSUE THREAD

**Issue by dazinator** [petabridge/dotnet-grafana-dashboards#12]
After importing this dashboard, it looks like the metric names used in the queries aren't aligning..
the dashboard queries use for example `dotnet_assemblies_count` where as the metric names from my prom (and the OTEL collector) are coming through as `process_runtime_dotnet_assemblies_count` e.g there is an added "process_runtime" prefix to mine.

This also aligns with what I see when I export them to a local aspire dashboard over GRPC i.e they come through with the "process_runtime_" prefix.
I wonder what the source of this discrepancy might be?

**Comment by Aaronontheweb** [comment]
@dazinator which versions of the OTEL instrumentation libraries are you using?

**Comment by dazinator** [comment]
packages are:

- OpenTelemetry.Instrumentation.AspNetCore v1.9.0
- OpenTelemetry.Instrumentation.Process v1.12.0
- OpenTelemetry.Instrumentation.Runtime v.1.9.0
- OpenTelemetry.Instrumentation.Http v1.12.0-beta.1

When debugging locally, the application emits to a local aspire dashboard

```
# otel collector
aspire-dashboard:
  image: mcr.microsoft.com/dotnet/aspire-dashboard:9.3
  #environment:    
  ports:
    - 18888:18888
    - 4317:18889
  networks:
    - default
    - telemetry
  deploy:
    replicas: 1
    restart_policy:
      condition: any
      delay: 10s
    resources:
      limits:
        cpus: '0.50'
        memory: '200M'
      reservations:
        cpus: '0.1'
        memory: '50M'
```
